### ISSUE TITLE
how do you use multiple gpu (only in 1 server?)

### ISSUE THREAD

**Issue by seanko29** [pmh9960/iColoriT#1]
Good afternoon.

Your code works great even with 1 GPU.
I want to set the gpu to 4 gpus but I tried to change --world_size 4 in argument of train.py but the system seems to use only 1 gpu.
If I want to use more than 1 gpu, what part of the code should I change or add on? It seems that your code has DDP around line 200. 

Thank you in advance!

**Comment by YeolJ00** [comment]
Hi, thanks for your interest in our work.

Concerning DDP in a single server, you can simply run
```
bash scripts/train.sh {GPU_IDS} {MASTER_PORT}
```

For example,

```
bash scripts/train.sh 0,1,2,3 4885
```
should work fine.
