### ISSUE TITLE
How to add a user defined hint point via command line using infer.py?

### ISSUE THREAD

**Issue by Nexirus** [pmh9960/iColoriT#2]
Hello, how to define a hint point directly by command line arguments instead of using GUI demo? Seems it is fixed in infer.py.

**Comment by YeolJ00** [comment]
Hi Nexirus,

The current code does not support a functioning CLI for evaluating single images. 
You'll have to modify some lines in ```infer.py```, specifically the bool hints that come from 
```
(images, bool_hints), targets, names = batch
```
in line [152](https://github.com/pmh9960/iColoriT/blob/main/infer.py#L152), to customize hints for each image.

However, we do have an interacitve hint generator  in [```hint_generator.py```](https://github.com/pmh9960/iColoriT/blob/0f1045df8b7b78a8c33511970a46fb61c758fe36/hint_generator.py#L46) which can be used for evaluating validation sets, which allows you to interactively generate hints used for evaluating the whole dataset.

Hope this helps!
Any PLs are welcome

Jooyeol
