### ISSUE TITLE
How to colorize without giving the hints, just pass the grey image and get the colored image?

### ISSUE THREAD

**Issue by mushtaqpatel0505** [pmh9960/iColoriT#3]
How to colorize without giving the hints, just pass the grey image and get the colored image

**Comment by mushtaqpatel0505** [comment]
@YeolJ00 @niceDuckgu @pmh9960

**Comment by YeolJ00** [comment]
Our model is not specifically trained for unconditional colorization, but you can still obtain a colorized image without providing any hints.
Have you tried it in the demo or the code? You simply don't pass any hints.

**Comment by mushtaqpatel0505** [comment]
Yeah, for some images its working well (colorizing the grey image) but for some images it is showing the grey image as it is

**Comment by mushtaqpatel0505** [comment]
Do I need to train on the old family photo? Could you tell me the procedure for using current checkpoints? base, small or tiny

**Comment by YeolJ00** [comment]
For some images, the initial results may still be grey since it is not trained to do that.
If you with to train an unconditional model, you can use the following command, given that you have all the training data ready.

```
bash scripts/train.sh --num_hint_range 0
```

Also, in order to use the small and tiny model, you would have to change the model type with the following argument.

```
bash scripts/infer.sh --model icolorit_small_4ch_patch16_224 --model path/to/your/checkpoint
```

**Comment by mushtaqpatel0505** [comment]
Could I train the "icolorit_base_4ch_patch16_224" checkpoint further on the coco, place365 ? not from scratch

**Comment by YeolJ00** [comment]
Yes you can, simply use the --resume argument and load the pretrained model.
I strongly suggest reading through the arguments in main.py.

**Comment by mushtaqpatel0505** [comment]
How to run on single image?

**Comment by YeolJ00** [comment]
Please refer to [the demo](https://github.com/pmh9960/iColoriT/tree/main/iColoriT_demo) for a GUI.
Also, PLEASE provide information when posting a question with information related to **_what you have tried_**, **_what the errors were_** and **_the enviornent_** you are running on.

**Comment by mushtaqpatel0505** [comment]
How to run on the single image without GUI in the terminal/command prompt?
